[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"

[dev]
  command = "npm run start"
  port = 8888

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200