backend:
  name: git-gateway
  branch: main # Defina o branch onde seu conteúdo será armazenado

media_folder: "img" # Pasta onde as imagens serão armazenadas
public_folder: "/img" # Caminho para as imagens públicas

editor:
  preview: false # Desabilita a visualização ao editar

collections:
  - name: "projects"
    label: "Projetos"
    folder: "projects" # Pasta onde os arquivos dos projetos serão armazenados
    create: true # Permite criar novos projetos
    fields:
      - { name: "title", label: "Título", widget: "string" }
      - { name: "description", label: "Descrição", widget: "text" }
      - { name: "image", label: "Imagem", widget: "image" } # Widget para imagem
      - { name: "link", label: "Link", widget: "string" }
      - { name: "date", label: "Data", widget: "datetime" }
